version: '3.5'

x-zou-build: &zou-build
    image: zou:${ZOU_VERSION:-latest}
    build:
        context: ./zou
        args:
            ZOU_VERSION: ${ZOU_VERSION:-latest}
            PREVIEW_FOLDER: ${PREVIEW_FOLDER:?}
            TMP_DIR: ${TMP_DIR:-/tmp/zou}

services:
    nginx:
        image: nginx:${KITSU_VERSION:-latest}
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
            args:
                KITSU_VERSION: ${KITSU_VERSION:-latest}

    zou-app:
        <<: *zou-build

    zou-event:
        <<: *zou-build
       
    zou-jobs:
        <<: *zou-build
